In [1]:
import numpy as np
import pandas as pd

In [ ]:
array1 = np.array([12,34,56,82])

In [ ]:
array1

array([12, 34, 56, 82])

In [ ]:
array1[2]

56

In [ ]:
array1[1:3]

array([34, 56])

In [ ]:
array1[1]='Hari'

ValueError: ignored

In [ ]:
array1[1]=13

In [ ]:
array1

array([12, 13, 56, 82])

In [ ]:
array1.ndim

1

In [ ]:
type(array1)

numpy.ndarray

In [ ]:
array2 = np.array([[12,23,54],[32,45,46]])
array2

array([[12, 23, 54],
       [32, 45, 46]])

In [ ]:
array2.ndim

2

In [ ]:
array2[1]

array([32, 45, 46])

In [ ]:
array2[1][0:2]

array([32, 45])

In [ ]:
array2.min(),array2.max(),np.sqrt(array2)

(12,
 54,
 array([[3.46410162, 4.79583152, 7.34846923],
        [5.65685425, 6.70820393, 6.78232998]]))

In [ ]:
type(array2)

numpy.ndarray

In [ ]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.arange(20,40)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [ ]:
np.arange(-20,40,6)

array([-20, -14,  -8,  -2,   4,  10,  16,  22,  28,  34])

In [ ]:
np.arange(40,20)

array([], dtype=int64)

In [ ]:
np.arange(40,20,-2)

array([40, 38, 36, 34, 32, 30, 28, 26, 24, 22])

In [ ]:
array2[-2][-1]

54

In [ ]:
np.linspace(12,34,16)

array([12.        , 13.46666667, 14.93333333, 16.4       , 17.86666667,
       19.33333333, 20.8       , 22.26666667, 23.73333333, 25.2       ,
       26.66666667, 28.13333333, 29.6       , 31.06666667, 32.53333333,
       34.        ])

In [ ]:
# Pandas ---> 2 parts (Series, Dataframe)

In [ ]:
demo1 = pd.Series(np.arange(3,6))
demo1

0    3
1    4
2    5
dtype: int64

In [ ]:
demo2 = pd.Series(np.arange(12,15))
demo2

0    12
1    13
2    14
dtype: int64

In [ ]:
demo3 = pd.DataFrame([demo1,demo2])
demo3

0   1   2
0   3   4   5
1  12  13  14

In [ ]:
demo3.T

0   1
0  3  12
1  4  13
2  5  14

In [2]:
dummy = {'Name':['Hari','Saumya','Srikanth','Shivani','Shivam',np.nan],
         'Age':[27,34,np.nan,29,11,52],
         'Track':('AI','ML','CAD',np.nan,np.nan,'Full stack')}

dummy

{'Name': ['Hari', 'Saumya', 'Srikanth', 'Shivani', 'Shivam', nan],
 'Age': [27, 34, nan, 29, 11, 52],
 'Track': ('AI', 'ML', 'CAD', nan, nan, 'Full stack')}

In [3]:
df = pd.DataFrame(dummy)
df

Name   Age       Track
0      Hari  27.0          AI
1    Saumya  34.0          ML
2  Srikanth   NaN         CAD
3   Shivani  29.0         NaN
4    Shivam  11.0         NaN
5       NaN  52.0  Full stack

In [4]:
df

Name   Age       Track
0      Hari  27.0          AI
1    Saumya  34.0          ML
2  Srikanth   NaN         CAD
3   Shivani  29.0         NaN
4    Shivam  11.0         NaN
5       NaN  52.0  Full stack

In [5]:
df.Name

0        Hari
1      Saumya
2    Srikanth
3     Shivani
4      Shivam
5         NaN
Name: Name, dtype: object

In [6]:
df['Name']

0        Hari
1      Saumya
2    Srikanth
3     Shivani
4      Shivam
5         NaN
Name: Name, dtype: object

In [7]:
type(df)

pandas.core.frame.DataFrame

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    5 non-null      object 
 1   Age     5 non-null      float64
 2   Track   4 non-null      object 
dtypes: float64(1), object(2)
memory usage: 272.0+ bytes


In [9]:
df.isnull()

Name    Age  Track
0  False  False  False
1  False  False  False
2  False   True  False
3  False  False   True
4  False  False   True
5   True  False  False

In [10]:
df.isnull().sum()

Name     1
Age      1
Track    2
dtype: int64

In [11]:
# loc & iloc

In [12]:
df.loc[0:2,'Name':'Age']

Name   Age
0      Hari  27.0
1    Saumya  34.0
2  Srikanth   NaN

In [13]:
df.iloc[0:3,0:2]

Name   Age
0      Hari  27.0
1    Saumya  34.0
2  Srikanth   NaN

In [14]:
df

Name   Age       Track
0      Hari  27.0          AI
1    Saumya  34.0          ML
2  Srikanth   NaN         CAD
3   Shivani  29.0         NaN
4    Shivam  11.0         NaN
5       NaN  52.0  Full stack

In [15]:
df.isnull().sum()

Name     1
Age      1
Track    2
dtype: int64

In [16]:
df.drop(['Name'],axis=0)

KeyError: ignored

In [19]:
df = df.drop(['Name'],axis=1)

In [20]:
df

Age       Track
0  27.0          AI
1  34.0          ML
2   NaN         CAD
3  29.0         NaN
4  11.0         NaN
5  52.0  Full stack

In [21]:
df['Age'].mean()

30.6

In [22]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [23]:
df

Age       Track
0  27.0          AI
1  34.0          ML
2  30.6         CAD
3  29.0         NaN
4  11.0         NaN
5  52.0  Full stack

In [25]:
df['Track'] = df['Track'].fillna('CAD')

In [26]:
df

Age       Track
0  27.0          AI
1  34.0          ML
2  30.6         CAD
3  29.0         CAD
4  11.0         CAD
5  52.0  Full stack